### ISSUE TITLE
error

### ISSUE THREAD

**Issue by deeaadd** [colby57/VMP-Imports-Deobfuscator#1]
![image](https://github.com/colby57/VMP-Imports-Deobfuscator/assets/163608099/8dbe9413-3dd1-4b6e-9d05-a1bb16d4e234)

и чё?

**Comment by deeaadd** [comment]
> did u fix it?

no

**Comment by colby57** [comment]
Если смотреть лишь на названия секций, то вероятно, у Вас исполняемый файл накрыт VMProtect версией <= 3.5.1, с которым тулза должна справляться на 100%, значит влияют какие-то другие факторы на работоспособность. Отправьте, пожалуйста, файл сюда в Telegram: @colby57re, чтобы я мог сам проверить.

**Comment by colby57** [comment]
Судя по предоставленной информации, исполняемый файл обладает минимальным набором защиты от протектора (Виртуализация EP) и не имеет защиты импортов, что и объясняет, почему инструмент ничего не исправлял, закрыто.
